import { Container } from "@mui/material";
import Box from "@mui/material/Box";
import Head from "next/head";
import MenuIcon from "@mui/icons-material/Menu";
import Typography from "@mui/material/Typography";
import Button from "@mui/material/Button";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container
          sx={{
            color: "whitesmoke",
            height: "100vh",
          }}
        >
          <Box
            sx={{
              p: 2,
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
            }}
          >
            <Typography
              sx={{
                fontSize: "Large",
              }}
            >
              Just a Landing Page
            </Typography>
            <MenuIcon
              sx={{
                cursor: "pointer",
              }}
            ></MenuIcon>
          </Box>
          <Typography
            sx={{
              fontWeight: 600,
              mt: { xs: 3, sm: 10, md: 15 },
              textAlign: "right",
              px: 10,
            }}
            variant="h2"
          >
            It&apos;s just landing page
          </Typography>
          <Typography
            sx={{
              textAlign: "right",
              p: 10,
              pt: 6,
            }}
            variant="h4"
          >
            You won&apos;t find anything fancy here
          </Typography>
          <Box
            sx={{
              display: "flex",
              justifyContent: "end",
              mr: 15,
            }}
          >
            <Button
              size="large"
              sx={{
                display: { xs: "none", sm: "flex" },
                color: "whitesmoke",
                borderColor: "whitesmoke",
                ":hover": { borderColor: "white", background: "#9B3DB9" },
              }}
              variant="outlined"
            >
              CTA(not really)
            </Button>
          </Box>
        </Container>

      </main>
      <Container
          sx={{
            color: "whitesmoke",
            height: "100vh",
          }}
        ></Container>
    </>
  );
}
