import { Container, Grid, Paper } from "@mui/material";
import Box from "@mui/material/Box";
import Head from "next/head";
import MenuIcon from "@mui/icons-material/Menu";
import Typography from "@mui/material/Typography";
import Button from "@mui/material/Button";

export default function Home() {
  const cardTitles = ["Just", "Landing", "Page"];
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container
          sx={{
            color: "whitesmoke",
            height: "100vh",
          }}
        >
          <Box
            sx={{
              p: 2,
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
            }}
          >
            <Typography
              sx={{
                fontSize: "Large",
              }}
            >
              Just a Landing Page
            </Typography>
            <MenuIcon
              sx={{
                cursor: "pointer",
              }}
            ></MenuIcon>
          </Box>
          <Typography
            sx={{
              fontWeight: 600,
              mt: { xs: 3, sm: 10, md: 15 },
              textAlign: "right",
              px: 10,
            }}
            variant="h2"
          >
            It&apos;s just landing page
          </Typography>
          <Typography
            sx={{
              textAlign: "right",
              p: 10,
              pt: 6,
            }}
            variant="h4"
          >
            You won&apos;t find anything fancy here
          </Typography>
          <Box
            sx={{
              display: "flex",
              justifyContent: "end",
              mr: 15,
            }}
          >
            <Button
              size="large"
              href="#Services"
              sx={{
                display: { xs: "none", sm: "flex" },
                color: "whitesmoke",
                borderColor: "whitesmoke",
                ":hover": { borderColor: "white", background: "#9B3DB9" },
              }}
              variant="outlined"
            >
              CTA(not really)
            </Button>
          </Box>
        </Container>
      </main>
      <Typography
        id="Services"
        variant="h1"
        sx={{
          textAlign: "center",
          my: 5,
          color: "#9B3DB9",
        }}
      >
        Seriously
      </Typography>
      <Grid
        container
        spacing={2}
        sx={{
          color: "whitesmoke",
          height: "100vh",
          mt: 10,
          textAlign: "center",
        }}
      >
        {cardTitles.map((item, index) => (
          <Grid item xs={12} md={4} key={index}>
            <Paper elevation={5}>
              <Typography
                variant="h2"
                sx={{
                  color: "black",
                  p: 1,
                }}
              >
                {item}
              </Typography>
              <Typography
                variant="h5"
                sx={{
                  fontSize: "17px",
                  p: 3,
                }}
              >
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis
                dignissimos cum architecto magnam ullam animi nostrum amet quos
                expedita, aspernatur adipisci at mollitia enim dolor molestiae
                magni culpa rerum facere unde cupiditate? Dignissimos, possimus!
                Sint consequatur cum sed tempore consectetur.
              </Typography>
              <Button
                variant="contained"
                href="#"
                sx={{
                  mb: 3,
                }}
              >
                Back to the top
              </Button>
            </Paper>
          </Grid>
        ))}
      </Grid>
    </>
  );
}
